/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : IDL.Int,
  'hiringNeeds' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearSubmissions' : IDL.Func([IDL.Text], [], []),
  'getAllSubmissions' : IDL.Func([IDL.Text], [IDL.Vec(Submission)], ['query']),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : IDL.Int,
    'hiringNeeds' : IDL.Text,
  });
  
  return IDL.Service({
    'clearSubmissions' : IDL.Func([IDL.Text], [], []),
    'getAllSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };