/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';

export interface Submission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'company' : string,
  'timestamp' : bigint,
  'hiringNeeds' : string,
  'formSource' : string,
}
export interface CareerApplication {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'position' : string,
  'coverLetter' : string,
  'timestamp' : bigint,
}
export interface JobListing {
  'id' : bigint,
  'title' : string,
  'jobType' : string,
  'location' : string,
  'description' : string,
  'skills' : string,
  'isInternship' : boolean,
  'duration' : string,
  'stipend' : string,
  'isActive' : boolean,
  'createdAt' : bigint,
}
export interface _SERVICE {
  'clearSubmissions' : ActorMethod<[string], undefined>,
  'getAllSubmissions' : ActorMethod<[string], Array<Submission>>,
  'getAllCareerApplications' : ActorMethod<[string], Array<CareerApplication>>,
  'getAllJobListings' : ActorMethod<[string], Array<JobListing>>,
  'getActiveJobs' : ActorMethod<[], Array<JobListing>>,
  'submitForm' : ActorMethod<[string, string, string, string, string], bigint>,
  'submitCareerApplication' : ActorMethod<[string, string, string, string, string], bigint>,
  'createJobListing' : ActorMethod<[string, string, string, string, string, string, boolean, string, string], bigint>,
  'toggleJobActive' : ActorMethod<[string, bigint], boolean>,
  'deleteJobListing' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
